[package]
name = "ibuilder_derive"
version = "0.1.0"
authors = ["Edoardo Morassutto <edoardo.morassutto@gmail.com>"]
edition = "2018"

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro-error = "1.0"

[lib]
proc-macro = true